Test only for "do" syntax, instead of "let"
compat-table/compat-table pull request #1008
Opened 2017-01-20 11:46 UTC by sheerun

Currently this test verifies not only "do" syntax, but also "let".

I'm changing "let" to "var" so only "do" is tested..

2017-01-20 12:38 UTC, chicoxyzzy approved these changes
LGTM

2017-01-20 12:43 UTC, zloirock commented
Hmm... `var` unlike `let` is not block scoped, `do` is a block. It will work, but I'm not sure that it will be a correct example.

2017-01-20 12:54 UTC, chicoxyzzy commented
we also can just omit any variables here. @zloirock what do you think about
```js
return do {
  if (true) {
    42;
  } else {
    'Pan Galactic Gargle Blaster';
  }
} === 42;
```
?

2017-01-20 16:47 UTC, ljharb commented
Are there any implementations that would pass this test with var, but not with let?

Unless there is one, I think leaving let is best.

2017-01-20 17:00 UTC, zloirock commented
@chicoxyzzy yep, as an option.

2017-01-20 18:52 UTC, ljharb commented
I think part of the test is that the do expression creates a scope. A block-scoped variable is required to test that. Any of these changes will be testing fewer things.

2017-01-23 19:17 UTC, chicoxyzzy commented
@sheerun please run `npm run build` and add changes to this PR

2017-01-23 23:38 UTC, ljharb requested changes

2017-01-23 23:38 UTC, ljharb commented on data-esnext.js
> +      var x = 23;
This must be a block-level variable to properly test block scope - in other words, it must be `let` or `const`.

Why do you think this is an important change to make? Does there exist any implementation that supports do expressions but not let/const?

2017-01-24 00:42 UTC, sheerun commented on data-esnext.js
> +      var x = 23;
I've just noticed that it might test something it's not supposed to, and sent PR. Your call

2017-01-24 00:58 UTC, ljharb commented on data-esnext.js
> +      var x = 23;
In this case I'm claiming it is supposed to be testing that.

2017-03-18 19:41 UTC, domenic commented on data-esnext.js
> +      var x = 23;
do expressions aren't specified, but once they are, it's not even clear they'll support var declarations inside of them.

2017-03-19 12:34 UTC, closed without merging