Add MDN links to tests (#973)
compat-table/compat-table pull request #1063
Opened 2017-04-01 15:07 UTC by KTamas

Implements #973 for all tabs. I asked someone at Mozilla, and he said, that based on his reading of the [Mozilla branding guide](https://www.mozilla.org/en-US/styleguide/identity/mozilla/branding/), our usage of the logo is OK here, and I agree with him.

2017-04-01 15:14 UTC, KTamas commented
also,  it looks a lot better now with the logo.
<img width="358" alt="screenshot 2017-04-01 17 13 51" src="https://cloud.githubusercontent.com/assets/48946/24579889/983423c6-16fe-11e7-8d39-ab0ad751c0cc.png">

2017-04-01 16:46 UTC, ljharb requested changes

2017-04-01 16:46 UTC, ljharb commented on build.js
> +            name += ' <a href="' + t.mdn + '"><img src="/mdn.png" width="15" height="13" /></a>&nbsp;';
Let's please add an "alt" to the image and a "title" to the link, for a11y

2017-04-01 16:46 UTC, ljharb commented on build.js
> +        name += ' <a href="' + t.mdn + '"><img src="/mdn.png" width="15" height="13" /></a>&nbsp;';
Could the link html be stored in only one place, or perhaps better, a function that takes an href? (This one needs a11y too)

2017-04-01 16:46 UTC, ljharb commented on build.js
> +          subtestName += ' <a href="' + subtest.mdn + '"><img src="/mdn.png" width="15" height="13" /></a>&nbsp;';
a11y

2017-04-02 07:23 UTC, KTamas commented
@ljharb I've made the changes.

2017-04-02 07:27 UTC, ljharb approved these changes
LGTM

2017-04-03 04:01 UTC, zloirock commented
LGTM

2017-04-03 04:50 UTC, merged