Consolidate items on esintl tab (issue #1062)
compat-table/compat-table pull request #1068
Opened 2017-04-04 17:56 UTC by afmenez

This patch implements the suggestion on issue #1062.  I grouped similar issues together to simplify the page.

But I found one issue that may block this patch: #1067.

2017-04-04 18:29 UTC, ljharb requested changes

2017-04-04 18:29 UTC, ljharb commented on data-esintl.js
> +	{
i think you may want to `s/\t/  /g` in this patch?

2017-04-04 19:03 UTC, afmenez commented
I did the tab/space replace as requested by @ljharb , but I am not able to reply on the review.

2017-04-06 12:01 UTC, chicoxyzzy approved these changes

2017-04-06 15:46 UTC, ljharb commented
I'm currently blocking based on https://github.com/kangax/compat-table/issues/1062#issuecomment-291633517

2017-05-16 12:37 UTC, afmenez commented
Closing due to opposition by @ljharb .

2017-05-16 12:37 UTC, closed without merging