Add Duktape 2.1 results
compat-table/compat-table pull request #1077
Opened 2017-04-15 18:57 UTC by svaarala

- Add results for Duktape 2.1
- Move duktape engines in environments.json to fix their HTML layout grouping (they were grouped under "mobile" for some reason)

2017-04-15 19:23 UTC, chicoxyzzy approved these changes

2017-04-19 19:54 UTC, afmenez requested changes
Removing the redundancies as described in the comments would simplify this patch a lot.

2017-04-19 19:54 UTC, afmenez commented on data-es2016plus.js
> +          duktape21: true,
You don't need to add every version here.  What is true for `duktape20` is also true for `duktape20` and all following versions.

2017-04-19 19:54 UTC, afmenez commented on environments.json
> +    "full": "Duktape 2.0.x",
I believe you could drop de ".x", it is implicit in the other browsers listed here.

2017-04-19 19:56 UTC, svaarala commented on data-es2016plus.js
> +          duktape21: true,
Ok, I'll make that change. But what metadata tells that duktape21 is a newer version of duktape20? There doesn't seem to be explicit metadata to that effect in environments.json. Or is it simply string sort based?

2017-04-19 19:57 UTC, svaarala commented on environments.json
> +    "full": "Duktape 2.0.x",
Ok, sounds good.

2017-04-19 20:04 UTC, afmenez commented on data-es2016plus.js
> +          duktape21: true,
I believe this is the purpose of the "family": "Duktape" field.

2017-04-19 20:11 UTC, svaarala commented on data-es2016plus.js
> +          duktape21: true,
Right, but how does one know X is newer than Y in the same family? I guess it's based on ordering in environments.json, i.e. same family but later in the file is newer?

2017-04-19 20:12 UTC, svaarala commented on data-es2016plus.js
> +          duktape21: true,
In any case the results are correct with the proposed change, so I'll apply that change to all the data files and update the pull. Thanks!

2017-04-19 20:35 UTC, svaarala commented
Suggested changes made, rebased and pushed.

2017-04-19 20:40 UTC, svaarala commented
Lint failed due to a duplicate key; fixed that.

2017-04-19 20:41 UTC, afmenez approved these changes
LGTM

2017-04-19 20:42 UTC, svaarala commented
The fix caused a HTML change and a Travis error from that. Hopefully both are now fixed :)

2017-04-19 20:44 UTC, svaarala commented
Ok, everything seems to pass now.

2017-04-19 20:50 UTC, afmenez approved these changes
LGTM

2017-04-21 07:49 UTC, merged