Add Chrome 60
compat-table/compat-table pull request #1084
Opened 2017-04-21 05:23 UTC by sscotth

2017-04-21 07:47 UTC, chicoxyzzy requested changes

2017-04-21 07:47 UTC, chicoxyzzy commented on data-esnext.js
> +        chrome60: true,
That's not true for Canary 60.0.3077.0

2017-04-21 08:42 UTC, sscotth commented on data-esnext.js
> +        chrome60: true,
Are you sure?

<img width="1037" alt="screen shot 2017-04-21 at 3 39 48 am" src="https://cloud.githubusercontent.com/assets/1010488/25269983/80cacf8c-2644-11e7-8bb2-cbb37783e556.png">

2017-04-21 08:49 UTC, chicoxyzzy commented on data-esnext.js
> +        chrome60: true,
Yes I'm pretty sure.
<img width="685" alt="screen shot 2017-04-21 at 10 46 53" src="https://cloud.githubusercontent.com/assets/1507086/25270165/e7288860-267f-11e7-9f56-4153846431aa.png">

Canary has A/B testing as was discussed before in older issues and PRs so maybe you are just the one of those lucky testers :)

2017-04-21 15:10 UTC, sscotth commented on data-esnext.js
> +        chrome60: true,
Interesting. I actually tried it on two (macOS) computers. I'll remove it.

2017-04-21 16:13 UTC, afmenez commented
How about retiring some old versions when a new one is added?  Chrome 50 was released more than a year ago, I believe anything older than that should be tagged with "obsolete:very" ...

2017-04-21 18:27 UTC, sscotth commented
That sounds more appropriate for a separate issue/pull request.

2017-04-24 13:55 UTC, chicoxyzzy approved these changes
I am ready to merge this after resolving conflicts 👍

2017-04-26 00:08 UTC, chicoxyzzy commented
Thank you @sscotth!

2017-04-26 00:09 UTC, merged