Unify the version naming convention
compat-table/compat-table pull request #1100
Opened 2017-05-12 07:29 UTC by mgol

So far some browsers were just omitting a dot in the version string and some
replaced it by an underscore. This commit changes all those versions to use
the underscore translation. This will reduce confusion; with some environments
using rapidly increasing major version numbers it becomes hard to distinguish
"41" from "4.1" when both are translated to "41" in the browser name.

The only exception is Duktape which needs to have names maching keys matching
what Duktape.version reports.

Also:
### 1)
Rename Duktape shortcuts from "DUK 20" to "DUK 2.0" & "DUK 21" to "DUK 2.1"

The previous versions were incorrect. Lots of engines have high major version
numbers so version 21 sounded plausible.

### 2)
Change iOS 10.0-10.3 to 10.0-10.2

iOS 10.3 was incorrectly included in a group with 10.0-10.2.

2017-05-12 08:24 UTC, ljharb approved these changes
We should fix the duktape result generation as well.

2017-05-12 08:30 UTC, mgol commented
> We should fix the duktape result generation as well.

This means there will be no direct matching between the key we use and the one reported by `Duktape.version`. Is that OK?

2017-05-12 08:34 UTC, ljharb commented
`Duktape.version` reports `duktape20`? O.o

2017-05-12 08:38 UTC, mgol commented
Unfortunately, yes...

2017-05-12 08:39 UTC, mgol commented
Hmm, no, actually it seems the comment is not 100% correct. What it actually reports is:
```
duk> Duktape.version
= 20100
```
Even weirder but then if we already have to transform it we might as well add an underscore.

2017-05-12 08:41 UTC, ljharb commented
yeah, that's a really stupid version string; it should use semver. I see no value in trying to match that.

2017-05-12 08:50 UTC, mgol commented
It's not even a string, it's a number. :)

2017-05-12 12:06 UTC, mgol commented
@ljharb Should I change that script in this PR and unify Duktape entries as well? Or in a new one>

2017-05-12 14:52 UTC, ljharb commented
Let's do another commit in this pr

2017-05-12 15:44 UTC, mgol commented
@ljharb PR updated.

2017-05-12 15:56 UTC, ljharb approved these changes

2017-05-15 17:56 UTC, afmenez commented on environments.json
> -  "safari51": {
This will conflict with my patch on #1099

2017-05-15 17:57 UTC, afmenez commented on environments.json
> +  "safari7_1_8": {
This is not Safari 7.1.8, but Safari 7.1 & Safari 8.  Also fixed on my patch on #1099

2017-05-15 17:58 UTC, afmenez requested changes
It would be really nice if you could revert the Safari changes so we can merge my more complete patch for Safari (#1099) without conflicts.

2017-05-15 18:40 UTC, mgol commented
@afmenez You mean Safari & iOS changes, don't you?

@ljharb Does that sound OK to you? I can revert those particular changes.

2017-05-15 18:43 UTC, afmenez commented
Yep, I did a larger change on Safari and iOS, adding some versions and results, and it already included all the changes you did.  If you revert just these parts, I believe both of our patches will be able to merge.  :)

2017-05-15 19:33 UTC, ljharb commented on environments.json
> -  "safari51": {
Do you think it'd be easier to merge yours first, and then rebase this one? or would it be easier to merge this, and rebase yours on top?

2017-05-15 19:35 UTC, afmenez commented on environments.json
> -  "safari51": {
I believe both would be about the same amount of work.  But I pushed my patch first... :)

2017-05-15 19:43 UTC, mgol commented on environments.json
> -  "safari51": {
@ljharb I can wait for the @afmenez's patch to be landed & then rebase mine. I'm fine with solving those merge conflicts, I just hope I won't have to do that multiple times.

2017-05-15 20:45 UTC, ljharb commented on environments.json
> -  "safari51": {
ok, sounds good

2017-05-15 21:08 UTC, mgol commented
PR rebased.

2017-05-16 00:53 UTC, merged