use the faster to install google-closure-compiler-js
compat-table/compat-table pull request #1106
Opened 2017-05-31 21:41 UTC by graingert

2017-05-31 21:43 UTC, ljharb requested changes
Thanks, seems like a good change.

2017-05-31 21:43 UTC, ljharb commented on build.js
> +          output = "" + child_process.execSync('./node_modules/.bin/google-closure-compiler-js ' +
we shouldn't ever be (or have been) hardcoding `node_modules` - let's use `which('google-closure-compiler-js')` and https://www.npmjs.com/package/npm-which instead?

2017-05-31 21:46 UTC, graingert commented on build.js
> +          output = "" + child_process.execSync('./node_modules/.bin/google-closure-compiler-js ' +
require('npm-which')(__dirname) or process.cwd() ?

2017-05-31 21:46 UTC, ljharb commented on build.js
> +          output = "" + child_process.execSync('./node_modules/.bin/google-closure-compiler-js ' +
`process.cwd()`, i think, since all commands should be run from project root (assuming both work)

2017-05-31 21:47 UTC, graingert commented on build.js
> +          output = "" + child_process.execSync('./node_modules/.bin/google-closure-compiler-js ' +
everything in this file hardcodes node_modules, and I don't want to touch everything in this PR

2017-05-31 21:48 UTC, ljharb commented on build.js
> +          output = "" + child_process.execSync('./node_modules/.bin/google-closure-compiler-js ' +
alright, fair enough - we can leave it to a separate PR

2017-05-31 21:48 UTC, ljharb approved these changes

2017-05-31 23:39 UTC, chicoxyzzy approved these changes

2017-06-13 19:53 UTC, merged

2017-06-13 19:53 UTC, chicoxyzzy commented
Thank you @graingert!