Add Safari 11
compat-table/compat-table pull request #1108
Opened 2017-06-05 22:57 UTC by chicoxyzzy

2017-06-06 04:25 UTC, ljharb reviewed
How are you installing Safari 11 to test this? I don't have it available on my Mac OS app update; it's not on browserstack; iOS hasn't released with it yet.

2017-06-06 12:53 UTC, chicoxyzzy commented
@ljharb I have Apple Developer Account. It's developer beta. I have both MacOS High Sierra and iOS 11 on my devices.

2017-06-07 16:54 UTC, afmenez requested changes
Almost there.

2017-06-07 16:54 UTC, afmenez commented on environments.json
> +    "unstable": false
Was it released already?  I was under the impression that it is still in beta...

2017-06-07 16:54 UTC, afmenez commented on environments.json
> +    "release": "2017-06-05",
I believe it was not released yet, so this date seems wrong...

2017-06-07 17:55 UTC, afmenez approved these changes
LGTM

2017-06-07 18:02 UTC, merged

2017-06-07 18:04 UTC, ljharb commented on environments.json
> +    "unstable": false
good call; beta should be considered unstable.

2017-06-07 18:34 UTC, chicoxyzzy commented on environments.json
> +    "unstable": false
Yes, I fixed that. Thank you @afmenez