Add node 8
compat-table/compat-table pull request #1119
Opened 2017-06-28 19:39 UTC by existentialism

Part of fixing:
https://github.com/babel/babel-preset-env/issues/361

2017-06-28 22:43 UTC, ljharb approved these changes

2017-06-29 17:15 UTC, mgol requested changes

2017-06-29 17:15 UTC, mgol commented on environments.json
> +    "short": "Node &gt;=8 &lt;8.1.2",
Why not just `Node 8`? Entries like that go out of date pretty quickly (in fact, it's already out of date as Node 8.1.3 is out). Upper bounds are needed once we know a new version introduces a v8 bump.

2017-06-29 18:21 UTC, mgol approved these changes

2017-06-30 23:03 UTC, merged

2017-06-30 23:03 UTC, chicoxyzzy commented
Thank you!