Update Safari TP and WebKit
compat-table/compat-table pull request #1128
Opened 2017-07-07 06:42 UTC by Constellation

2017-07-11 14:49 UTC, chicoxyzzy requested changes

2017-07-11 14:49 UTC, chicoxyzzy commented on data-es5.js
> -      webkit: true,
Let's keep browsers info explicit

2017-07-13 15:57 UTC, Constellation commented on data-es5.js
> -      webkit: true,
OK, I've just updated the patch.

2017-07-14 10:00 UTC, chicoxyzzy commented
Thank you!

2017-07-14 10:00 UTC, merged