Reviewing Opera versions and results, retiring ancient versions
compat-table/compat-table pull request #1129
Opened 2017-07-08 20:55 UTC by afmenez

I am adding separate entries for all Opera versions between 7.0 and 12.1.
Due to issue #1127 , I was only able to test with versions 10.50 and later, so no results for previous versions.
Also notice that due to issue #1118 , there are a lot of wrong results on the generated html (there were before, and there are more now).  Actually, I am not sure this patch can be merged until the issue is fixed.

2017-07-11 14:47 UTC, chicoxyzzy requested changes

2017-07-11 14:47 UTC, chicoxyzzy commented on data-es5.js
> -      opera12_10: true,
Let's keep things explicit where possible (keep `opera12_10: true`) here and elsewhere

2017-07-11 16:47 UTC, afmenez commented on data-es5.js
> -      opera12_10: true,
Sorry, do you want me to add "true" to all tested versions?  This would be a lot of work with little to no gain.

2017-07-11 17:16 UTC, chicoxyzzy commented on data-es5.js
> -      opera12_10: true,
No, just those which was already marked as `true`

2017-07-11 19:45 UTC, afmenez commented
Reverted the result consolidation.

2017-07-12 05:22 UTC, chicoxyzzy approved these changes

2017-07-12 12:50 UTC, afmenez commented
Notice that even after restoring previous explicit results, this patch still introduces more errors on the generated HTML due to #1118 (there are some wrong values already).

2017-08-08 17:44 UTC, afmenez commented
As I was rebasing this patch, I noticed that it causes some wrong results but it fixes a lot more.  Even with #1118 still pending, I believe this patch is a gain.

2017-08-08 18:08 UTC, merged

2017-08-08 18:32 UTC, afmenez commented
Tks!