Promoting class fields to Stage 3
compat-table/compat-table pull request #1140
Opened 2017-07-31 18:26 UTC by afmenez

The "class fields" proposal was promoted to Stage 3 last week.  I believe none of the other changes affect this table because there are no tests for them yet (see #1034).

2017-07-31 18:50 UTC, chicoxyzzy approved these changes

2017-07-31 19:38 UTC, ljharb requested changes
The shorthand syntax was deferred to a separate proposal, so that test needs to be deleted.

2017-07-31 20:30 UTC, afmenez commented
Sorry, can you elaborate?  Do you mean one of the subtests must be split to a separate proposal? Which subtest?  Which separate proposal?

2017-07-31 20:39 UTC, chicoxyzzy commented
Does new proposal for shorthand syntax of class fields exist?

2017-07-31 20:48 UTC, ljharb commented
The shorthand proposal does not yet exist; for now we should delete or fix any test that does not have `this.` in front of the #.

2017-07-31 20:54 UTC, afmenez commented
So, the only change would be in the last test (private fields initializers)
```
class C {
-   #x = 42;
+   this.#x = 42;
    x() {
        return this.#x;
    }
}
return new C().x() === 42;
```
Is that it?

2017-07-31 22:20 UTC, ljharb commented
Yep!

It'd also be good (but not necessary) to also add a test that accesses a private field on another instance of the same class.

2017-07-31 22:24 UTC, afmenez commented
I did fix the shorthand use, but I left the additional tests to a separate patch, since it is not the intention of this one.

2017-07-31 23:24 UTC, ljharb requested changes

2017-07-31 23:24 UTC, ljharb commented on data-esnext.js
> +          this.#x = 42;
oh crap sorry, this is my bad :-( the shorthand is `#x` in code - but in the class body, `#x = 42` is already correct (－‸ლ) apologies

2017-08-01 08:53 UTC, ljharb commented
k, i excised the extra commit, sorry about that

2017-08-01 08:54 UTC, merged

2017-08-01 13:10 UTC, afmenez commented
No problem.