Temporary workaround platformtype column widths problem by harcoding …
compat-table/compat-table pull request #1199
Opened 2017-10-17 20:54 UTC by afmenez

This is a temporary workaround for the "platform type" column widths problem (#1146), by harcoding the correct sizes.

2017-10-17 23:40 UTC, chicoxyzzy approved these changes

2017-10-18 00:57 UTC, ljharb requested changes
I don't think a temporary workaround is beneficial; this will just create unnecessary diff churn in the next PR, until we fix #1146.

2017-10-20 13:05 UTC, afmenez commented
Adding a temporary workaround for issue #1198, by removing the empty column header.

2017-10-25 12:37 UTC, afmenez commented
I still believe that this patch would be beneficial.  Yes, the pre-filled column witdhs will degrade soon, but the fix to the zero-width header will last.

2017-10-25 13:28 UTC, ljharb approved these changes

2017-10-25 13:28 UTC, merged

2017-10-25 13:35 UTC, afmenez commented
Tks!