Firefox 60 released
compat-table/compat-table pull request #1297
Opened 2018-05-09 14:00 UTC by afmenez

Firefox 60 released today.

2018-05-09 15:34 UTC, ljharb approved these changes

2018-05-10 11:15 UTC, chicoxyzzy commented on environments.json
> +    "full": "Firefox 60",
It should be `Firefox 60  ESR`

2018-05-10 11:43 UTC, chicoxyzzy requested changes
The full name should be Firefox 60 ESR. Otherwise LGTM

2018-05-10 13:15 UTC, afmenez commented
I believe this may be confusing.  On every ESR release before this one, we only added the ESR suffix when the next version came out.

2018-05-10 13:41 UTC, chicoxyzzy commented
Hm, I don't understand what exactly is confusing. Firefox 60 is ESR so we should reflect this in compatibility table. 

https://www.mozilla.org/en-US/firefox/organizations/

![image](https://user-images.githubusercontent.com/1507086/39872502-79c8cb50-5468-11e8-98ce-aedfc6896651.png)

2018-05-10 13:53 UTC, afmenez commented
You see, this is exactly the confusing part. As you can see in the graph, Firefox ESR (in yellow) are separate releases from the mainline (in green).  Firefox 60 IS not an ESR release, it HAS an ESR release.  Most people are in the main release train and don't even know what the ESR is, and that's why it may be confusing.
The rendering engine is identical for the normal and ESR releases, so I don't believe we should have 2 separate entries.

2018-05-10 14:10 UTC, chicoxyzzy commented
We don't reflect rendering engine features in our table. Regular release and ESR have the same SpiderMonkey version. Sometimes some features could be disabled in ESR version. Actually it happened once with WebAssembly (it was disabled in 52 ESR) which is also not reflected in table. If something like this will happen in future, we can add note about this.

2018-05-11 02:21 UTC, chicoxyzzy approved these changes

2018-05-11 02:21 UTC, merged