SIMD is no longer in JavaScript (moved to WebAssembly).
compat-table/compat-table pull request #1320
Opened 2018-06-28 18:39 UTC by brianblakely

Per TC39 documentation: https://github.com/tc39/ecmascript_simd

2018-06-28 18:49 UTC, ljharb requested changes
The proposal is inactive, but the feature still exists. Instead of deleting it, please move it to nonstandard.

2018-06-28 20:09 UTC, ljharb requested changes

2018-06-28 20:09 UTC, ljharb commented on data-non-standard.js
> +      (function (y) { return y; }).arity === 2;
this is incorrect; the arity should be 2 only when there's 2 arguments.

2018-06-28 20:32 UTC, chicoxyzzy requested changes
yes, please move it to non-standard page

2018-06-28 20:35 UTC, chicoxyzzy reviewed
Oops. Now I see you did it already. Please make changes according to @ljharb's comments

2018-06-28 20:37 UTC, chicoxyzzy approved these changes
Oh. I should work little bit less to prevent burnout :)
LGTM

2018-06-28 22:27 UTC, ljharb requested changes
One more change, and it'd be great if you could rebase down to one commit :-)

2018-06-28 22:27 UTC, ljharb commented on data-non-standard.js
> -      (function (x, y) { return y; }).arity === 2;
this function is fine continuing to return `y`; i'm not sure why this line needs a change at all. can you revert it?

2018-07-06 17:34 UTC, ljharb approved these changes

2018-07-06 17:37 UTC, merged