Implement the ArrayBuffer.prototype.transfer() proposal
compat-table/compat-table pull request #1368
Opened 2018-11-06 17:08 UTC by afmenez

I am trying to implement the `ArrayBuffer.prototype.transfer()` tests, but I have some questions:

-Are the tests correct?
-I don't have the results for Safari, can anyone run it?
-I have added significance: 'small' but I am not sure what is the relative importance of this feature;

TIA

2018-11-06 17:16 UTC, chicoxyzzy commented
> -I don't have the results for Safari, can anyone run it?

they are both `false`

2018-11-06 17:22 UTC, afmenez commented
Fixed indentation and added Safari results.

2018-11-06 18:23 UTC, ljharb requested changes

2018-11-06 18:23 UTC, ljharb commented on data-esnext.js
> +        return typeof ArrayBuffer.prototype.transfer === 'function';
these just test for existence; we should instead/also be testing the functionality.

In other words, the tests should ensure that it actually truncates and detaches a buffer.

2018-11-06 18:49 UTC, afmenez commented on data-esnext.js
> +        return typeof ArrayBuffer.prototype.transfer === 'function';
I based my tests on some of the "BigInt" tests, which do the same. The "Metadata reflection API", "zones", "Frozen Realms API" and "Promise.try" and  tests are also implemented like this.

2018-11-06 18:51 UTC, ljharb commented on data-esnext.js
> +        return typeof ArrayBuffer.prototype.transfer === 'function';
Then those should have been fleshed out too :-)

2018-11-06 18:54 UTC, zloirock commented
Some time ago we had [this](https://github.com/kangax/compat-table/commit/fa5b98ac90a6ad4444140b4b5150a564717c2d9e) test.

2018-11-06 19:46 UTC, ljharb approved these changes

2018-11-06 19:47 UTC, ljharb commented
cc @domenic for correctness of the tests

2018-11-17 21:10 UTC, chicoxyzzy approved these changes

2018-11-19 15:48 UTC, afmenez commented
Rebased

2018-11-19 15:51 UTC, merged