Firefox 68 released
compat-table/compat-table pull request #1481
Opened 2019-07-08 22:54 UTC by afmenez

Firefox 68 will be released tomorrow.

2019-07-09 13:53 UTC, chicoxyzzy reviewed
Numeric Separators and Promise.allSettled are not available by default in Firefox 68 and Firefox 69

2019-07-09 13:55 UTC, chicoxyzzy requested changes

2019-07-09 13:55 UTC, chicoxyzzy commented on environments.json
> +    "full": "Firefox 68",
```suggestion
    "full": "Firefox 68 ESR",
```

2019-07-09 13:55 UTC, chicoxyzzy commented on environments.json
> +    "short": "FF 68",
```suggestion
    "short": "FF 68 ESR",
```

2019-07-09 15:16 UTC, afmenez commented on environments.json
> +    "full": "Firefox 68",
68 ESR wasn't released yet.

2019-07-09 15:16 UTC, afmenez commented on environments.json
> +    "short": "FF 68",
68 ESR wasn't released yet.

2019-07-09 15:17 UTC, afmenez commented
You are correct, both features  seem to be "beta and nightly only" for now.  I'll update the patch later today.

2019-07-09 16:31 UTC, chicoxyzzy commented on environments.json
> +    "short": "FF 68",
https://www.mozilla.org/en-US/firefox/68.0esr/releasenotes/

2019-07-09 16:33 UTC, chicoxyzzy commented
> both features seem to be "beta and nightly only" for now

Both are disabled in Beta and Developer Edition and enabled in Nightly only

2019-07-10 01:22 UTC, afmenez commented
Fixed all the wrong results (found another one on the non-standard page).  The 68 ESR builds are not released yet, we can update this later (in a separate PR).

2019-07-10 03:32 UTC, chicoxyzzy commented
ESR was released see https://github.com/kangax/compat-table/pull/1481#discussion_r301681697

2019-07-10 12:44 UTC, afmenez commented
Yep, the release notes for all versions is usually available in advance, but the installer it is not available on the [main download page](https://www.mozilla.org/en-US/firefox/organizations/) yet.
Also, current 60 ESR are not being upgraded yet.
The ESR is  usually released only after the main release is already "unthrottled" and is considered trusted enough.  It takes a few days.

2019-07-10 13:59 UTC, chicoxyzzy commented
I don't see any reasons why we shouldn't add ESR now.

> Also, current 60 ESR are not being upgraded yet.

It will get updates until 68.2 ESR will be released according to calendar https://wiki.mozilla.org/Release_Management/Calendar

2019-07-10 14:05 UTC, chicoxyzzy commented
Also you can download 68 ESR here: https://www.mozilla.org/en-US/firefox/organizations/all/?q=English%20(US)

2019-07-11 01:01 UTC, afmenez commented on environments.json
> +    "short": "FF 68",
Done.

2019-07-11 06:18 UTC, chicoxyzzy approved these changes

2019-07-11 06:24 UTC, merged