Safari TP89 is out, with ?? operator suport
compat-table/compat-table pull request #1490
Opened 2019-08-09 23:08 UTC by afmenez

https://webkit.org/blog/9497/release-notes-for-safari-technology-preview-89/

2019-08-10 00:10 UTC, ljharb approved these changes

2019-08-12 12:27 UTC, chicoxyzzy requested changes
Nullish coalescing is not enabled by default in TP89. See https://twitter.com/rkirsling/status/1159568652397502464

2019-08-12 15:46 UTC, afmenez commented
Changed the result to "flagged" and added a note on enabling it.

2019-08-12 15:55 UTC, chicoxyzzy approved these changes
LGTM. Though I'd change note wording a bit:
The feature have to be enabled via JSC runtime flag `__XPC_JSC_useNullishCoalescing=true`

2019-08-12 16:05 UTC, ljharb commented on data-esnext.js
> +    safaritp: {val: 'flagged', note_id: "safari-nullish", note_html: "You can flip it on like this: <code>__XPC_JSC_useNullishCoalescing=true && open -a 'Safari Technology Preview'</code>."},
no &&, or it won’t work
```suggestion
    safaritp: {val: 'flagged', note_id: "safari-nullish", note_html: "You can flip it on like this: <code>__XPC_JSC_useNullishCoalescing=true open -a 'Safari Technology Preview'</code>."},
```

2019-08-12 16:17 UTC, afmenez commented on data-esnext.js
> +    safaritp: {val: 'flagged', note_id: "safari-nullish", note_html: "You can flip it on like this: <code>__XPC_JSC_useNullishCoalescing=true && open -a 'Safari Technology Preview'</code>."},
Done

2019-08-12 16:19 UTC, ljharb approved these changes

2019-08-12 16:58 UTC, merged