Add Node 13.0
compat-table/compat-table pull request #1520
Opened 2019-10-21 12:32 UTC by zloirock

2019-10-21 14:25 UTC, ljharb requested changes

2019-10-21 14:25 UTC, ljharb commented on environments.json
> +    "release": "2019-10-22",
node 13 hasn’t been released yet

2019-10-21 14:32 UTC, zloirock commented on environments.json
> +    "release": "2019-10-22",
Yes, today is `2019-10-21`, and?...

2019-10-22 14:05 UTC, chicoxyzzy approved these changes
LGTM pending release

2019-10-22 16:17 UTC, ljharb approved these changes

2019-10-22 16:18 UTC, merged