Add optional function call to optional chaining
compat-table/compat-table pull request #1585
Opened 2020-02-13 20:08 UTC by ilogico

I noticed the syntax for the optional function call wasn't being tested `f?.()`.
I also slightly changed the test for optional method call to better guarantee `this` is correct.

2020-02-13 21:40 UTC, ljharb approved these changes
Pending confirmation that all the results here have been manually verified.

2020-02-14 13:29 UTC, ilogico commented
I didn't confirm the results manually, I assumed they were the same as the rest.
I did confirm them on the latest Firefox, Chrome and TypeScript.

2020-02-15 00:45 UTC, ljharb commented
In that case, please remove all the results you didn't confirm manually :-) future PRs can add the results as they're tested.

2020-02-17 11:11 UTC, ilogico commented
I removed the results I couldn't confirmed.
I kept the false results which are guaranteed to be false (ie11 and firefox < 73)

2020-02-17 11:33 UTC, chicoxyzzy approved these changes
Both optional method call and optional function call tests return `true` in Safari 13.1 Beta and Firefox 74 Beta. Though we can add these results in the following PR.

2020-02-17 11:36 UTC, chicoxyzzy commented on data-es2016plus.js
> -          chrome78: {val: 'flagged', note_id: "chrome-optional-chaining"},
I think that this result is still valid, we should re-check it

2020-02-17 11:37 UTC, chicoxyzzy commented on data-es2016plus.js
> -          babel7corejs2: true,
This result is still valid

2020-02-17 11:41 UTC, chicoxyzzy requested changes
Thinking again, all removed test results from optional method call tests should be added again. I've rechecked them all manually.

2020-02-17 15:31 UTC, ilogico commented
Should I add them again?

2020-02-17 16:00 UTC, chicoxyzzy commented
@ilogico yes please

2020-02-17 16:06 UTC, ilogico commented
Done

2020-02-17 17:41 UTC, chicoxyzzy commented
Oh, sorry, I mentioned only optional method call test results, not optional function call. But that's ok, I'll check them too. Thanks!

2020-02-17 17:48 UTC, chicoxyzzy approved these changes
Optional function call results are also correct. Thank you again!

2020-02-17 17:48 UTC, merged