Edge 80 released
compat-table/compat-table pull request #1586
Opened 2020-02-15 14:15 UTC by afmenez

Edge 80 released, matches Chrome 80.

2020-02-15 15:20 UTC, ljharb approved these changes

2020-02-17 11:22 UTC, chicoxyzzy requested changes

2020-02-17 11:22 UTC, chicoxyzzy commented on environments.json
> +    "release": "2020-02-12",
```suggestion
    "release": "2020-02-07",
```

2020-02-17 17:50 UTC, chicoxyzzy approved these changes

2020-02-17 18:01 UTC, merged