Public static class fields supported on Firefox 75
compat-table/compat-table pull request #1593
Opened 2020-03-20 21:56 UTC by afmenez

Public static class fields will be supported on Firefox 75:
https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#JavaScript

2020-03-20 23:37 UTC, ljharb commented on data-esnext.js
> +        firefox74:false,
```suggestion
        firefox74: false,
```

2020-03-20 23:37 UTC, ljharb commented on data-esnext.js
> +        firefox74:false,
```suggestion
        firefox74: false,
```

2020-03-20 23:38 UTC, ljharb requested changes
Seems like this shouldn’t merge until April 7th?

2020-03-21 01:02 UTC, afmenez commented
Why the wait?

2020-03-21 01:22 UTC, ljharb commented
In case it doesn’t end up being released on that date. We generally don’t include things in advance of their being released, i think?

2020-03-21 01:37 UTC, afmenez commented
Yes, we do.  We have the "unstable" tab for that.  There are 2 unstable
versions of Firefox.  And Chrome.  And Safari.

On Fri, Mar 20, 2020 at 10:22 PM Jordan Harband <notifications@github.com>
wrote:

> In case it doesn’t end up being released on that date. We generally don’t
> include things in advance of their being released, i think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kangax/compat-table/pull/1593#issuecomment-601973064>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKEQ6DTUDDEYFF5O2T4KG3RIQJFVANCNFSM4LQVHGFA>
> .
>

2020-03-21 01:42 UTC, ljharb approved these changes

2020-03-21 01:42 UTC, ljharb approved these changes

2020-03-21 10:51 UTC, chicoxyzzy approved these changes

2020-03-21 10:52 UTC, merged