Add iOS for replaceAll
compat-table/compat-table pull request #1653
Opened 2020-06-29 01:27 UTC by pustovalov

webkit.org says `replaceAll` support from iOS 13.1
https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/

MDN says `replaceAll` support from ios 13.4
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll

What resource should I believe?)

https://en.wikipedia.org/wiki/IOS_13

2020-06-29 06:24 UTC, ljharb approved these changes
Please only add results you’ve explicitly tested; we don’t trust documentation :-)

2020-06-29 06:25 UTC, ljharb requested changes
whoops, meant to request changes pending confirmation of manual testing

2020-06-29 11:02 UTC, pustovalov commented
Demo: https://codesandbox.io/s/zealous-rubin-8zh3r


`iOS 13_2`, failed
https://monosnap.com/direct/U3sgH4kKZDGpUS0WPWnNBIocPpVTgy


`iOS 13_3`, failed:
https://monosnap.com/direct/rcIYIO9hhcs7IhEbrCWzEd5QQ9VFX0


`iOS 13_4_1`, success
https://monosnap.com/direct/pyvHbo1jDbuxRzHJvBi9BzWvPaxwn3

I have not found `13_4_0`, should I add `13_4_1` if you can only test on this version?

2020-06-29 15:16 UTC, pustovalov commented
checked, iOS support `replaceAll` from `13.4`

2020-06-29 18:39 UTC, ljharb approved these changes
Thanks!

2020-07-06 14:17 UTC, chicoxyzzy approved these changes

2020-07-06 18:26 UTC, merged