add note about tail call optimisation support in some older ES6 versions
compat-table/compat-table pull request #1778
Opened 2021-11-25 10:34 UTC by ngyl88

The tail call optimisation support in some older ES6 version, but no longer pursued by V8.

It might be better to replace the existing footnote [8] with footnote [9].
Footnote [5] is created, as it's more towards V8 engine rather than Node servers.

2021-11-25 15:31 UTC, ljharb requested changes

2021-11-25 15:31 UTC, ljharb commented on data-es6.js
> +    + 'have been removed has been removed. See: '
```suggestion
    + 'have been removed. See: '
```

2021-11-25 15:31 UTC, ljharb commented on data-es6.js
> +    + 'in certain version of Node.js. Since Node.js 8.2.1, the V8 flags '
```suggestion
    + 'in certain versions of Node.js. Since Node.js 8.2.1, the V8 flags '
```

2022-01-11 05:22 UTC, ljharb requested changes

2022-01-11 05:22 UTC, ljharb commented on data-es6.js
> +  note_id: 'proper-tail-call-optimisation',
this feature is called "proper tail calls". It is not an optimization and must not be described as one.
```suggestion
  note_id: 'proper-tail-calls',
```

2022-01-11 05:57 UTC, ngyl88 commented
@ljharb Conflicts are resolved. Some hiccups just now. Thanks!

2022-01-11 06:48 UTC, ljharb approved these changes
Seems good

2022-01-11 06:52 UTC, ljharb requested changes
oops - this needs a rebase down to one commit, and unfortunately because you made the PR from a fork that isn't yours, i can't force push to it. can you please add me to https://github.com/ngyl88-tw/compat-table so i can land this PR? (please do *not* close this PR and/or open another one)

2022-01-12 05:24 UTC, ngyl88 commented
> oops - this needs a rebase down to one commit, and unfortunately because you made the PR from a fork that isn't yours, i can't force push to it. can you please add me to https://github.com/ngyl88-tw/compat-table so i can land this PR? (please do _not_ close this PR and/or open another one)

Sure, @ljharb . I'm not sure on the right way to do this merge and rebase from the upstream properly. Thanks for helping.

2022-01-12 05:26 UTC, ljharb commented
No worries at all, thanks for obliging! (in the future if you keep your forks on your own username, you won't run into this github bug)

2022-01-12 05:26 UTC, ljharb approved these changes

2022-01-14 11:57 UTC, chicoxyzzy approved these changes

2022-01-14 17:15 UTC, merged