add new safari, edge, chrome, opera versions
compat-table/compat-table pull request #1831
Opened 2022-09-28 22:16 UTC by Eutrepe

Add new browser versions:

chrome: https://en.wikipedia.org/wiki/Google_Chrome_version_history
edge: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
safari: https://developer.apple.com/safari/technology-preview/release-notes/
opera: https://blogs.opera.com/desktop/
opera android: https://forums.opera.com/category/20/opera-for-android?sort=newest_to_oldest

2022-09-28 22:17 UTC, zloirock requested changes
Without adding compat data for them, it makes no sense.

2022-09-28 22:19 UTC, zloirock commented on environments.json
> +  "safari16": {
Between 15 and 16, 15.4 added some new ES features.

2022-09-28 22:25 UTC, zloirock commented on environments.json
> +  "ios16": {
The same about 15.4.

2022-09-28 23:02 UTC, Eutrepe commented
I checked the test results and made changes.

2022-09-28 23:16 UTC, zloirock commented
Safari 16 and the latest Safari TP added many new ES features, however, they are not covered by the `compat-table` test case. It's not related to this PR, so LGTM.

2022-09-28 23:16 UTC, zloirock approved these changes

2022-09-28 23:31 UTC, zloirock requested changes
I checked one more time. You missed some iOS versions and forgot to mark some browser versions as obsolete.

2022-09-28 23:51 UTC, ljharb approved these changes
We generally don’t block new versions on compat data since they auto inherit the previous version’s results. Why do we need to do so here?

2022-09-29 00:03 UTC, zloirock commented
@ljharb ~~we~~ you.

And it's the reason why `compat-table` no longer can't be considered as a proper compat data source.

And, as always, you had read only a couple of first comments and missed the last review.

2022-09-29 00:05 UTC, ljharb commented
No, me and @chicoxyzzy.

I agree with blocking on incorrect claims, but it’s perfectly fine if there’s a version whose data is accidentally incorrect - it’ll get fixed eventually.

Compat data doesn’t have to be, and simply can’t be, 100% correct at all times - it just has to be eventually correct, since it’s a moving target.

2022-09-29 00:12 UTC, zloirock commented
As always, you missed a part of the questions and comment only on all that you want. So is this fine for you? -)

![image](https://user-images.githubusercontent.com/2213682/192909668-b6075ae7-2b56-4d44-a629-774ccfbcb955.png)

With this approach, `compat-table` has lost its relevance - to 2019 it was almost complete - and it is not clear to me how projects like Babel now can still use a data source containing such outdated data.

2022-09-29 00:14 UTC, ljharb commented
If it’s incorrect, please file PRs to fix it. It’s not worsening the problem to frustrate contributors with atypical requirements.

Adding versions should always be done in a different PR than adding the data for them.

2022-09-29 00:20 UTC, zloirock commented
I'm curious why you bring this topic up here where it's fixed? Here already another issue -) I don't give a damn about your opinion, just like you don't care about mine - issues like this will be a pull request block.

2022-09-29 02:04 UTC, ljharb commented
That’s a very hostile way to interact with other maintainers. I do care about your opinion, but caring about someone’s opinion doesn’t mean one has to agree with it.

The majority of maintainers on this project have been running it a certain way. Until a majority of maintainers prefer something different, that will be the way the project is run. @chicoxyzzy, can you way in?

2022-09-29 04:38 UTC, zloirock commented
Even after the picture above, he still doesn't understand (or pretends?) that this is another issue...

2022-09-29 04:42 UTC, zloirock commented
> I do care about your opinion

[You have perfectly shown that you consider your opinion more important than the opinion of others.](https://github.com/kangax/compat-table/pull/1821#issuecomment-1228818107)

2022-09-29 06:47 UTC, Eutrepe commented
I added "obsolete" for more more browsers and added ios15.2 and ios15.4 (I think we don't need more)

2022-09-29 07:23 UTC, zloirock commented
@Eutrepe yes, sure. It seems you forgot to push it -)

2022-09-29 07:39 UTC, Eutrepe commented
Sorry, I have pushed now

2022-09-29 07:50 UTC, zloirock approved these changes

2022-09-29 07:50 UTC, zloirock commented
LGTM, thanks.

2022-09-29 07:50 UTC, merged