add `regexp-v-flag` compat data
compat-table/compat-table pull request #1852
Opened 2023-03-07 17:17 UTC by JLHwung

2023-03-30 17:25 UTC, afmenez commented
I have run the tests on Firefox 91 and 102, they don't work there either.

2023-03-30 18:25 UTC, JLHwung commented
@afmenez Thanks! I will add `firefox91` results and hopefully the `firefox102` result can be interpolated from 91 and 110.

2023-05-16 16:03 UTC, JLHwung commented
Moved to `es2016plus` now that the proposal is stage 4 as of the may meeting.

2023-05-16 16:25 UTC, zloirock commented on data-esnext.js
>  ];
It seems all changes in this file should be discarded.

2023-05-16 16:26 UTC, zloirock commented on esnext/index.html
>  </body>
In this file - too.

2023-05-16 16:32 UTC, zloirock requested changes
![image](https://github.com/kangax/compat-table/assets/2213682/8d8beff3-8599-489b-ad97-0a062f7b7be3)

2023-05-16 17:00 UTC, ljharb commented
It achieved stage 4 this morning.

2023-05-16 17:25 UTC, zloirock commented
@ljharb it's es2016+ table, so it should be renamed.

2023-05-16 17:27 UTC, ljharb commented
Why? It contains ES2016 and later, including ES2023 and the eventual ES2024.

2023-05-16 17:28 UTC, zloirock commented
Like the rest features, it should indicate the version of ES where it's added or will be added. Like the rest features from this table.

2023-05-16 17:30 UTC, ljharb commented
That version is unknown until the release is cut (which for ES2024 happens in March 2024), which is why the page has worked this way for the better part of a decade.

2023-05-16 17:30 UTC, JLHwung commented
The category here is copied from

https://github.com/kangax/compat-table/blob/09d24e559a39884eee5749e5a60c1e3cc859196b/data-es2016plus.js#L6782

I think `finished (stage 4)` was a thing, of course it is a transient category and we will probably replace it by "es2024 features" in the future. It is an editorial issue, do you mark ES2024 after a proposal is advanced to stage 4? Or do you mark ES2024 after the spec is actually updated.

2023-05-16 17:31 UTC, ljharb commented
@JLHwung we usually mark ESX in June X, when the edition is approved by Ecma, or in March X, when I've cut the candidate.

2023-05-16 17:33 UTC, zloirock commented
IIRC previous features were marked before that. Let it be, I don't care.

2023-05-16 17:33 UTC, zloirock approved these changes

2023-05-16 18:24 UTC, ljharb approved these changes

2023-05-16 18:26 UTC, merged