Implement the Array Grouping tests
compat-table/compat-table pull request #1930
Opened 2024-10-14 23:30 UTC by afmenez

I am not sure about the 'significance' field.

2024-10-15 00:08 UTC, ljharb requested changes

2024-10-15 00:08 UTC, ljharb commented on data-es2016plus.js
> +          return obj['even'][0] == 2 && obj['odd'][0] == 1;
```suggestion
          return !('toString' in obj) && obj.even[0] == 2 && obj.odd[0] == 1;
```
to ensure it's got a null prototype

2024-10-15 00:08 UTC, ljharb commented on data-es2016plus.js
> +          return map.get(even)[0]  == 2 && map.get(odd)[0]  == 1;
```suggestion
          return map instanceof Map && map.get(even)[0] === 2 && map.get(odd)[0] === 1;
```

2024-10-15 16:54 UTC, afmenez commented on data-es2016plus.js
> +          return obj['even'][0] == 2 && obj['odd'][0] == 1;
Done.

2024-10-15 16:54 UTC, afmenez commented on data-es2016plus.js
> +          return map.get(even)[0]  == 2 && map.get(odd)[0]  == 1;
Done.

2024-10-15 19:53 UTC, afmenez commented
I had to rebase to commit the requested changes, but now the comments are gone.

2024-10-17 18:57 UTC, chicoxyzzy approved these changes

2024-10-17 19:12 UTC, ljharb approved these changes

2024-10-17 19:13 UTC, merged