Added new passing tests for JerryScript 3.0.0
compat-table/compat-table pull request #1961
Opened 2024-12-17 09:10 UTC by gergocs

2024-12-17 22:36 UTC, afmenez requested changes
Please check the `obsolete` and `experimental` fields on `environments.json`.

2024-12-17 22:36 UTC, afmenez commented on environments.json
> +    "obsolete": true,
This is the current release, so it should be `"obsolete": false,`.  All the previous versions are more than 5 years old now, they should be `"obsolete": "very",`

2024-12-17 22:36 UTC, afmenez commented on environments.json
>      "obsolete": false,
3.0 is not released yet, so it should be `"unstable": true,`

2024-12-18 10:26 UTC, gergocs commented
The release will be today. I will let you know when the release is done.

2024-12-18 13:02 UTC, gergocs commented
JerryScript  3.0 has been [released](https://github.com/jerryscript-project/jerryscript/releases/tag/v3.0.0)

2024-12-18 13:22 UTC, afmenez approved these changes

2024-12-18 13:24 UTC, afmenez commented on environments.json
> +    "obsolete": true,
3.0 was released, so `"obsolete": true` is correct now.

2024-12-18 13:24 UTC, afmenez commented on environments.json
>      "obsolete": false,
3.0 was released, so `"obsolete": false` is correct now.

2025-02-06 09:40 UTC, ossy-szeged commented
> JerryScript 3.0 has been [released](https://github.com/jerryscript-project/jerryscript/releases/tag/v3.0.0)

1.5 months have passed since the release. Can we merge this PR?

2025-03-28 10:16 UTC, ossy-szeged commented
@ljharb @chicoxyzzy ping?

2025-03-28 17:21 UTC, ljharb commented
2 approvals are required, so as soon as @chicoxyzzy approves, I'll approve and land.

2025-05-15 20:04 UTC, gergocs commented
@chicoxyzzy ping?

2025-05-20 19:33 UTC, ljharb approved these changes

2025-05-20 19:33 UTC, merged