Use ES2016 snapshot links
compat-table/compat-table pull request #918
Opened 2016-09-22 15:28 UTC by chicoxyzzy

As per discussion from #828

Please check misc links in this PR because I'm not 100% all of them are ok.

cc @bterlson

2016-09-22 15:34 UTC, ljharb commented on data-es2016plus.js
> +    link: 'http://www.ecma-international.org/ecma-262/7.0/index.html#sec-createdynamicfunction',
This link seems useful to keep somewhere

2016-09-22 15:34 UTC, ljharb commented on data-es2016plus.js
> +    link: 'http://www.ecma-international.org/ecma-262/7.0/index.html#sec-generatorfunction-objects',
Also this

2016-09-22 15:34 UTC, ljharb commented on data-es2016plus.js
> +    link: 'http://www.ecma-international.org/ecma-262/7.0/index.html#sec-functiondeclarationinstantiation',
Etc

2016-09-22 15:35 UTC, ljharb requested changes
I like using snapshots, but we'd lose a lot of important information by erasing the links to meeting notes and github issues. Not sure what the best solution is.

2016-09-22 16:01 UTC, chicoxyzzy commented
@ljharb should I just add another field or just a comment or revert to old links?

2016-09-22 16:15 UTC, ljharb commented
I think all of those are good options - maybe we should change "link" to be an object of "link name" to "link url", and then we can display them all in the UI?

2016-09-22 16:54 UTC, bterlson commented
There are two concepts here: links to spec text, and links to supporting info. Spec text should probably have a "spec:" key, other links can go into a links array and be displayed as superscript footnotes or something?

2016-10-03 11:45 UTC, chicoxyzzy commented
Updated

2016-10-03 15:46 UTC, zloirock commented
LGTM

2016-10-03 15:51 UTC, zloirock commented
However, I think it would be better to make notes better readable, not just links with 2 words.

2016-10-03 15:53 UTC, zloirock commented
"Meeting notes" - from what meeting? "GitHub issue" - which issue from which repo? Etc.

2016-10-03 18:12 UTC, chicoxyzzy commented
OK I'll try to add more meaningful notes

2016-10-03 18:28 UTC, chicoxyzzy commented
Please let me know if I can improve footnotes even more

2016-10-03 18:34 UTC, zloirock commented
LGTM

2016-10-03 18:36 UTC, zloirock commented
Stop... Inconsistency
```
[9] TC39 meeting notes from 28 July, 2015.
[10] TC39 meeting notes from July 28, 2015.
```

2016-10-03 19:57 UTC, chicoxyzzy commented
thank you. fixed

2016-10-04 12:06 UTC, chicoxyzzy commented
I'm still not sure that current spelling in footnotes is good enough. @ljharb @bterlson can you re-review please?

2016-10-04 15:41 UTC, ljharb approved these changes

2016-10-04 17:18 UTC, merged