Remove obsolete FF Nightly footnote
compat-table/compat-table pull request #927
Opened 2016-10-04 20:23 UTC by chicoxyzzy

2016-10-04 20:28 UTC, zloirock commented
It can be useful for someone.

2016-10-04 20:36 UTC, chicoxyzzy commented
@zloirock in that case we should keep all Nightlies browsers versions data not only FF 45 and 48 Nightlies

2016-10-04 20:41 UTC, chicoxyzzy commented
also we shouldn't keep this data in footnote anyway IMO

2016-10-05 17:38 UTC, afmenez requested changes
I agree that the current implementation isn't good, but I believe your patch isn't perfect yet.

2016-10-05 17:38 UTC, afmenez commented on data-es2016plus.js
> -          firefox48: firefox.nightly,
This is implemented and is enabled by default only on nightly builds.  I believe the correct here would be to change firefox48 to "flag" and add a line with firefox52: nightly.

2016-10-05 17:38 UTC, afmenez commented on data-es2016plus.js
> -          firefox48: firefox.nightly,
This is implemented and is enabled by default only on nightly builds.  I believe the correct here would be to change firefox48 to "flag" and add a line with firefox52: nightly.

2016-10-05 17:38 UTC, afmenez commented on data-es2016plus.js
> -      firefox45: firefox.nightly,
I believe the correct here would be to change firefox45 to "flag", since it is what is implemented.

2016-10-05 17:38 UTC, afmenez commented on data-es2016plus.js
> -      firefox45: firefox.nightly,
I believe the correct here would be to change firefox45 to "flag", since it is what is implemented.

2016-10-05 23:56 UTC, chicoxyzzy commented
@afmenez changing `firefox.nightly` to `flag` seems incorrect. adding ff 52 to footnotes doesn't make any sense too

2016-10-06 13:36 UTC, afmenez commented
As I understand, these features are implemented but disabled by default, which is exactly what the flag tag means.
What is currently not nice is that if I open the test with the nightly version, I get different results from the ones listed, because the test says the features work, but the result table shows only the note.  Marking the features with the flag tag will improve this, because there will be a green corner on each result.  But ideally, the results would show as true for nightly to match with the test.

2016-10-06 14:49 UTC, chicoxyzzy commented
What I see here is that we have wrong results for FF 52 (this should be fix in another PR):
![](http://i.imgur.com/wpuxvsM.png)

What I see here is that O.values and O.entries are available in Nightly and this is exactly what FF 52 tests results show
![](http://i.imgur.com/sUmBIGp.png)

We can't mark feature as available under flag because this is not true for stable versions.
We should keep all unstable versions results if we want this information to be meaningful.

2016-10-06 14:53 UTC, chicoxyzzy commented
I don't agree with @zloirock that this info is useful, this info is hard to understand.

2016-10-06 15:41 UTC, ljharb commented
Useful and hard to understand aren't mutually exclusive. If it's hard to understand we should certainly make it easier, but having the data present is useful.

2016-10-06 15:51 UTC, chicoxyzzy commented
In my opinion it's reasonably useful and easy to understand if we will provide data only for last nightly version. I have no idea why does one need to use some nightly build of FF 45 and know it support exponential operator. Noone builds web applications for FF 45 Nightly. It's enough to know that _last_ Nightly support a feature.

2016-10-06 15:55 UTC, chicoxyzzy commented
What if only some versions of FF 45 Nightly support a feature and others don't? Should we keep builds info? I can agree that this might be useful info but I can't agree such complexity worth it.

2016-10-06 15:59 UTC, ljharb commented
I think we only need the latest nightly info for any given major version - iow we don't need builds info.

2016-10-06 16:02 UTC, chicoxyzzy commented
> I think we only need the latest nightly info for any given major version

don't sure that footnotes is a good place for this type of information

2016-10-11 00:02 UTC, chicoxyzzy commented
Ok, I give up this time

2016-10-11 00:02 UTC, closed without merging