fix sticky table header on chrome
compat-table/compat-table pull request #984
Opened 2016-12-15 20:32 UTC by Trias

position: sticky is supported on chrome but apparently buggy. so make it use the fallback. Also updated the jquery.floatThead.js dependency

2016-12-15 22:27 UTC, ljharb requested changes

2016-12-15 22:27 UTC, ljharb commented on master.js
> +  if(thead.css('position') === "sticky" && window.chrome){
`if (` and `) {`

2016-12-15 22:39 UTC, ljharb approved these changes
LGTM but it'd be great to rebase this down to fewer commits

2016-12-15 23:26 UTC, chicoxyzzy approved these changes
LGTM

2016-12-17 09:04 UTC, Trias commented
ok done. hope it's fine now :)

2016-12-20 11:42 UTC, chicoxyzzy commented
Thank you!

2016-12-20 11:42 UTC, merged

2016-12-20 14:58 UTC, mkoryak reviewed
Cool. I didn't know safari (of all browsers) now supports sticky. I'll have to pull this into floatthead